### ISSUE TITLE
not sending messages

### ISSUE THREAD

**Issue by Naiym223** [Its-Vichy/Discord-ChatBooster#6]
it's printing IDs but not sending any messages to my channels.. why is this?

**Comment by Its-Vichy** [comment]
Give more info

**Comment by Naiym223** [comment]
It doesn't send any messages to the channel IDs i put in the txt, it just
starts printing IDs in the cmd and doesn't do anything.

**Comment by Naiym223** [comment]
Why did you close my issue? It's not resolved
